import { Bank } from './types';

export const BANKS: Bank[] = [
  { id: '105', nameCyr: 'АИК банка', nameLat: 'AIK banka' },
  { id: '115', nameCyr: 'Јетел банка', nameLat: 'Yettel banka' },
  { id: '145', nameCyr: 'Адријатик банка', nameLat: 'Adriatic banka' },
  { id: '155', nameCyr: 'Халк банка', nameLat: 'Halkbank' },
  { id: '160', nameCyr: 'Банка Интеза', nameLat: 'Banka Intesa' },
  { id: '165', nameCyr: 'Адико банка', nameLat: 'Addiko banka' },
  { id: '170', nameCyr: 'Уникредит банка', nameLat: 'UniCredit banka' },
  { id: '190', nameCyr: 'Алта банка', nameLat: 'Alta banka' },
  {
    id: '200',
    nameCyr: 'Поштанска Штедионица',
    nameLat: 'Poštanska Štedionica',
  },
  { id: '205', nameCyr: 'НЛБ Комерцијална', nameLat: 'NLB Komercijalna' },
  { id: '220', nameCyr: 'Прокредит банка', nameLat: 'ProCredit banka' },
  { id: '265', nameCyr: 'Рајфајзен банка', nameLat: 'Raiffeisen banka' },
  { id: '295', nameCyr: 'Српска банка', nameLat: 'Srpska banka' },
  { id: '325', nameCyr: 'ОТП банка', nameLat: 'OTP banka' },
  { id: '340', nameCyr: 'Ерсте банка', nameLat: 'Erste banka' },
  { id: '370', nameCyr: 'Три банка', nameLat: 'Tri banka' },
  { id: '375', nameCyr: 'АПИ банка', nameLat: 'API banka' },
  { id: '380', nameCyr: 'Мира банка', nameLat: 'Mirabank' },
  { id: '385', nameCyr: 'Банка Кине', nameLat: 'Bank of China' },
  { id: '840', nameCyr: 'Управа за трезор', nameLat: 'Uprava za trezor' },
];

export const TRANSLATIONS = {
  cyr: {
    title: 'Генератор NBS IPS QR кôда',
    requiredNote:
      "Сва поља обележена звездицом (<span class='asterisk'>*</span>) морају бити попуњена.",
    fields: {
      R: 'Број рачуна примаоца',
      N: 'Назив примаоца плаћања',
      I: 'Износ новчаних средстава',
      P: 'Подаци о платиоцу',
      SF: 'Шифра плаћања',
      S: 'Сврха плаћања',
      RO: 'Позив на број одобрења',
    },
    btnGenerate: 'Генериши Кôд',
    btnSave: 'Сачувај',
    btnDelete: 'Обриши',
    drawerTitle: 'Сачувани кодови',
    emptyDrawer: 'Нема сачуваних кодова',
    validation: {
      mod97: 'Неисправан контролни број (последње две цифре).',
      bankNotFound: 'Банка није пронађена.',
      required: 'Ово поље је обавезно.',
      format: 'Неисправан формат.',
      accountLength: 'Рачун мора имати тачно 18 цифара.',
      invalidReference: 'Неисправан позив на број (провера модулом 97).',
      purposeTooLong: 'Сврха плаћања не може имати више од 35 карактера.',
      charactersRemaining: 'карактера преостало',
    },
    placeholders: {
      saveName: 'Унесите назив за чување...',
      accountNumber: '105-0000000000000-29',
      recipientName: 'нпр. Жика Жикић',
      amount: '545,95',
      payerData: 'нпр. Петар Петровић',
      purpose: 'нпр. плаћање рачуна',
      reference: 'нпр. 474654465',
    },
  },
  lat: {
    title: 'Generator NBS IPS QR kôda',
    requiredNote:
      "Sva polja obeležena zvezdicom (<span class='asterisk'>*</span>) moraju biti popunjena.",
    fields: {
      R: 'Broj računa primaoca',
      N: 'Naziv primaoca plaćanja',
      I: 'Iznos novčanih sredstava',
      P: 'Podaci o platiocu',
      SF: 'Šifra plaćanja',
      S: 'Svrha plaćanja',
      RO: 'Poziv na broj odobrenja',
    },
    btnGenerate: 'Generiši Kod',
    btnSave: 'Sačuvaj',
    btnDelete: 'Obriši',
    drawerTitle: 'Sačuvani kodovi',
    emptyDrawer: 'Nema sačuvanih kodova',
    validation: {
      mod97: 'Neispravan kontrolni broj (poslednje dve cifre).',
      bankNotFound: 'Banka nije pronađena.',
      required: 'Ovo polje je obavezno.',
      format: 'Neispravan format.',
      accountLength: 'Račun mora imati tačno 18 cifara.',
      invalidReference: 'Neispravan poziv na broj (provera modulom 97).',
      purposeTooLong: 'Svrha plaćanja ne može imati više od 35 karaktera.',
      charactersRemaining: 'karaktera preostalo',
    },
    placeholders: {
      saveName: 'Unesite naziv za čuvanje...',
      accountNumber: '105-0000000000000-29',
      recipientName: 'npr. Žika Žikić',
      amount: '545,95',
      payerData: 'npr. Petar Petrović',
      purpose: 'npr. plaćanje računa',
      reference: 'npr. 474654465',
    },
  },
};
